FROM nvcr.io/nvidia/tensorrt:25.11-py3

WORKDIR /workspace
COPY requirements.txt /workspace/requirements.txt
RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

COPY install_pi05.sh /workspace/install_pi05.sh
RUN ./install_pi05.sh